name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: "interview-hemant-sharma"
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: "github_actions-thir"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: List directory contents
        run: ls -la dist/
        shell: bash

      - name: cloudsmith cli install
        run: |
          pip3 install --upgrade cloudsmith-cli

      # This step handles the entire OIDC authentication flow automatically.
      # It gets a token from GitHub and exchanges it for a Cloudsmith token.
      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.4
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}     # Replace with your Cloudsmith workspace
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }} # Replace with your service account slug
          oidc-auth-only: 'true'

      - name: Push package to Cloudsmith using Action
        uses: cloudsmith-io/action@v0.6.14
        with:
          command: "push"
          format: "python"
          owner: "interview-hemant-sharma"
          repo: "staging"
          version: "any-version"
          #republish: "true" # needed ONLY if version is not changing
          file: "dist/*.tar.gz"
        


